#define BAUD_RATE 115200

#define WIFI_TIMEOUT 30000

#define CHARGER_ADDRESS "192.168.0.224"
#define CHARGER_MODBUS_PORT 502
#define CHARGER_UNIT_ID 1
#define CHARGER_MAX_CURRENT_IN_AMPERE 32
#define CHARGER_MIN_CURRENT_IN_AMPERE 6

#define P1_MAXLINELENGTH 1050

char telegram[P1_MAXLINELENGTH];

long ACTUAL_CONSUMPTION;
long ACTUAL_RETURNDELIVERY;

unsigned int currentCRC = 0;

#define CAPACITEITSTARIEF_IN_WATT 5000

#define LOAD_BALANCE_INTERVAL_IN_SECONDS 30

float p1meter_consumptions_in_watt[LOAD_BALANCE_INTERVAL_IN_SECONDS];
int measurement_index = 0;